# Generated by Django 4.2.5 on 2023-09-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_field1_mymodel_witnesses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
