# Generated by Django 4.2.5 on 2023-09-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near_miss', models.CharField(blank=True, choices=[('c', 'Safety Concern'), ('i', 'Safety Idea/Suggestion'), ('n', 'Near-Miss'), ('o', 'Other')], max_length=1, null=True)),
            ],
        ),
    ]
