# Generated by Django 4.2.5 on 2023-09-12 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='Witnesses',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='field3',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Departments',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Incident_report_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Location_Area',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Recommendation_step',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='Type_of_near_miss',
            field=models.CharField(choices=[('SC', 'Safety Concern'), ('SIG', 'Safety Idea/Suggestion'), ('NM', 'Near-Miss'), ('OT', 'Other')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
