# Generated by Django 4.2.5 on 2023-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0005_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Witnesses', models.CharField(max_length=100)),
                ('Departments', models.CharField(max_length=50)),
                ('Location_Area', models.CharField(max_length=50)),
                ('Incident_report_date', models.DateField()),
                ('Type_of_near_miss', models.CharField(choices=[('SC', 'Safety Concern'), ('SIG', 'Safety Idea/Suggestion'), ('NM', 'Near-Miss'), ('OT', 'Other')], max_length=20)),
                ('Description', models.CharField(max_length=500)),
                ('Recommendation_step', models.CharField(max_length=500)),
            ],
        ),
    ]
