# Generated by Django 4.2.5 on 2023-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Incident_report_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Recommendation_step',
            field=models.TextField(max_length=500),
        ),
    ]
