# Generated by Django 4.2.5 on 2023-09-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_incident_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Incident_report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
