# Generated by Django 4.2.5 on 2023-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_incident_safety_violated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Safety_violated',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Yes'), ('3', 'N/A')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Type_of_near_miss',
            field=models.CharField(choices=[('1', 'Safety Concern'), ('2', 'Safety Idea/Suggestion'), ('3', 'Near-Miss'), ('4', 'Other')], max_length=30, null=True),
        ),
    ]
